### PR TITLE
Fix flaky e2e test due to unfinalized message

### LINKED ISSUE #1805: e2e tests wait until message is finalized
We currently have flaky tests because we don't wait until a message is finalized before calling the relayer. On local tests finality period is near 0. That's why we have this race condition. 

Three options to solve this problem

1) If relayer crashes, retry
2) wait a fixed amount of time
3) wait until message is finalized and ready for execution.

I think 3) is the cleanest solution and we could even think about implementing this into the relayer. If not, as the status quo, we need to externally make sure that the relayer only runs after finalization.
Otherwise we could also implement the check into the e2e test shell script.

### PR DESCRIPTION
**Pull request by manuelwedler**
Closes #1805

There might be the case in the e2e tests that a message was not finalized yet and the relayer is already started. To align with the agent, the e2e tests should restart the relayer. For the implementation, I separated the execution of the relayer in a new python script.

### CODE REVIEW

**Review by istankovic — CHANGES_REQUESTED** [review]

File: docker/scripts/common.sh [hunk 1]
```diff
@@ -63,6 +63,26 @@ e2e_test_fill() {
...
+    local root=$(get_root_dir)
+    local l1_rpc=$1
+    local l2_rpc=$2
+    local network_config=$3
+    local privkey=$4
+    local txhash=$5
+    local relayer=${root}/relayer/relayer-node18-linux-x64
+    
+    echo Starting relayer...
+    timeout 5m bash -c "until ${relayer} --l1-rpc-url '$l1_rpc' \
```
Comment (istankovic) [inline docker/scripts/common.sh:76]: I think we should omit the timeout and let CircleCI's timeout handle that. In some cases even 5min may not be enough so let's just defer that to CircleCi.

Comment (manuelwedler) [reply docker/scripts/common.sh:76]: Sure we can do that.
I did it because you said the opposite in the issue: https://github.com/beamer-bridge/beamer/issues/1805#issuecomment-1547705673

File: scripts/e2e-test-relayer.py [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        )
+        return completed.returncode
+
+    with Sleeper(300) as sleeper:  # todo
+        while run_relayer() != 0:
+            sleeper.sleep(0.1)
+
+
+if __name__ == "__main__":
+    main()
```
[the remark this answers is not in the document]
Comment (manuelwedler) [reply scripts/e2e-test-relayer.py]: You mean the `scripts/common.sh` I guess. Moved the retries to there.

File: docker/scripts/common.sh (hunk 1 above)
Comment (istankovic) [reply docker/scripts/common.sh:76]: Yeah, I think I was not aware just how long this stuff can take when I wrote that comment. We may even have to increase the CircleCI timeout. :disappointed:

**Review by istankovic — APPROVED** [review]

File: docker/scripts/common.sh (hunk 1 above)
Comment (manuelwedler) [reply docker/scripts/common.sh:76]: We just talked in person and decided to merge and see if we run into issues with the timeout.
